//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePiece.Web.DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimeEpisode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnimeEpisode()
        {
            this.AnimeVideos = new HashSet<AnimeVideo>();
        }
    
        public int Id { get; set; }
        public int AnimeSeasonId { get; set; }
        public string Avatar { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual AnimeSeason AnimeSeason { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimeVideo> AnimeVideos { get; set; }
    }
}
