//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePiece.Web.DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public Nullable<int> ArticleCategoryId { get; set; }
        public string Avatar { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public string Description { get; set; }
        public bool IsActived { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string Slug { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ArticleCategory ArticleCategory { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
