//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePiece.Web.DataImport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnePieceEntities : DbContext
    {
        public OnePieceEntities()
            : base("name=OnePieceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnimeEpisode> AnimeEpisodes { get; set; }
        public virtual DbSet<AnimeSeason> AnimeSeasons { get; set; }
        public virtual DbSet<ArticleCategory> ArticleCategories { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<MangaChapter> MangaChapters { get; set; }
        public virtual DbSet<MangaSeason> MangaSeasons { get; set; }
        public virtual DbSet<MusicVideo> MusicVideos { get; set; }
        public virtual DbSet<NewsFeed> NewsFeeds { get; set; }
        public virtual DbSet<AnimeCategory> AnimeCategories { get; set; }
        public virtual DbSet<AnimeVideo> AnimeVideos { get; set; }
        public virtual DbSet<MangaImage> MangaImages { get; set; }
        public virtual DbSet<VideoLink> VideoLinks { get; set; }
    }
}
