//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePiece.Web.DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoLink
    {
        public int Id { get; set; }
        public Nullable<int> AnimeVideoId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public bool IsMainLink { get; set; }
        public int LinkType { get; set; }
        public string Note { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Url { get; set; }
        public Nullable<int> VideoId { get; set; }
        public int VideoQuality { get; set; }
    
        public virtual AnimeVideo AnimeVideo { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
