//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePiece.Web.DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int Id { get; set; }
        public string AlternativeLink { get; set; }
        public string AspectRatio { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public string Description { get; set; }
        public int Height { get; set; }
        public string Link { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int VideoQuality { get; set; }
        public int Width { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
